-- MySQL Script generated by MySQL Workbench
-- 08/04/15 21:38:36
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema exp
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `exp` ;

-- -----------------------------------------------------
-- Schema exp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `exp` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `exp` ;

-- -----------------------------------------------------
-- Table `exp`.`rules`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `exp`.`rules` ;

CREATE TABLE IF NOT EXISTS `exp`.`rules` (
  `rule_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `rule_name` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`rule_id`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `exp`.`keywords`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `exp`.`keywords` ;

CREATE TABLE IF NOT EXISTS `exp`.`keywords` (
  `keyword_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `keywords` VARCHAR(45) NULL COMMENT '关键词',
  `rules_rule_id` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`keyword_id`)  COMMENT '',
  INDEX `fk_keywords_rules1_idx` (`rules_rule_id` ASC)  COMMENT '',
  CONSTRAINT `fk_keywords_rules1`
    FOREIGN KEY (`rules_rule_id`)
    REFERENCES `exp`.`rules` (`rule_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `exp`.`materials`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `exp`.`materials` ;

CREATE TABLE IF NOT EXISTS `exp`.`materials` (
  `material_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `type` TINYINT(1) NULL COMMENT '1:文本 2：图片 3: 图文 4：语音 5：视频',
  `file_name` VARCHAR(500) NULL COMMENT '资源文件名',
  `title` VARCHAR(45) NULL COMMENT '图文-标题，图片-名称',
  `description` VARCHAR(500) NULL COMMENT '图文-描述',
  `pic_url` VARCHAR(500) NULL COMMENT '图文-封面，图片-地址',
  `media_id` VARCHAR(99) NULL COMMENT '',
  `author` VARCHAR(45) NULL COMMENT '图文-作者',
  `content` TEXT NULL COMMENT '图文-详情页内容，文本-回复消息',
  `source_url` VARCHAR(500) NULL COMMENT '图文-原文地址',
  `link_out` TINYINT(1) NULL COMMENT '是否跳转',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  PRIMARY KEY (`material_id`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `exp`.`replies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `exp`.`replies` ;

CREATE TABLE IF NOT EXISTS `exp`.`replies` (
  `reply_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NULL COMMENT '',
  `materials_material_id` INT(11) NOT NULL COMMENT '',
  `rules_rule_id` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`reply_id`)  COMMENT '',
  INDEX `fk_replies_materials_idx` (`materials_material_id` ASC)  COMMENT '',
  INDEX `fk_replies_rules1_idx` (`rules_rule_id` ASC)  COMMENT '',
  CONSTRAINT `fk_replies_materials`
    FOREIGN KEY (`materials_material_id`)
    REFERENCES `exp`.`materials` (`material_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_replies_rules1`
    FOREIGN KEY (`rules_rule_id`)
    REFERENCES `exp`.`rules` (`rule_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
